apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-petclinic-sa
  namespace: spring-petclinic
---
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-petclinic-role
  namespace: spring-petclinic
rules:
- apiGroups: ["security.openshift.io"]
  resourceNames: ["privileged","anyuid"]
  resources: ["securitycontextconstraints"]
  verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-petclinic-role-binding
  namespace: spring-petclinic
subjects:
- kind: ServiceAccount
  name: spring-petclinic-sa
  namespace: spring-petclinic
roleRef:
  kind: ClusterRole
  name: spring-petclinic-role
  apiGroup: rbac.authorization.k8s.io