apiVersion: apps/v1 
kind: Deployment
metadata:
   name: petclinic-mysql
   namespace: spring-petclinic
spec:
   replicas: 1
   selector:
      matchLabels:
         app: petclinic-mysql
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: petclinic-mysql
      spec:
         serviceAccountName: spring-petclinic-sa
         imagePullSecrets:
         - name: "regcred"         
         containers:
         - image: egapm/spring-petclinic:mysql-db
           imagePullPolicy: Always
           name: petclinic-mysql 
           env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
           ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
   name: petclinic-mysql
   namespace: spring-petclinic

spec:
   ports:
   - port: 3306 
     targetPort: 3306
   selector:
      app: petclinic-mysql
